// apps/angular-app/src/app/home/home.component.ts
import { Component, HostListener, Inject, OnInit } from '@angular/core';
import { Router } from '@angular/router';
import type { IAccountAPI, ITwitterAPI, Tweet } from '@hexademo/domain';
import { AccountAPI, TwitterAPI } from '../injections';

@Component({
	selector: 'app-home',
	templateUrl: './home.component.html',
	styleUrls: ['./home.component.scss'],
})
export class HomeComponent implements OnInit {
	username = '';

	message = '';

	tweets: Tweet[] = [];

	constructor(
		private router: Router,
		@Inject(TwitterAPI) private twitterAPI: ITwitterAPI,
		@Inject(AccountAPI) private accountAPI: IAccountAPI
	) {}

	ngOnInit(): void {
		if (!this.accountAPI.isAuthenticated()) {
			this.router.navigate(['/']);
		} else {
			this.username = this.accountAPI.getUsername();
			this.getTweets();
		}
	}

	async getTweets() {
		this.tweets = await this.twitterAPI.listTweets();
	}

	@HostListener('document:tweetCreated', ['$event'])
	async refresh() {
		await this.getTweets();
	}

	@HostListener('tweetSubmited', ['$event'])
	async create(event: CustomEvent) {
		this.message = event.detail;
		await this.twitterAPI.tweet(this.message);
		this.clearForm();
	}

	@HostListener('tweetLiked', ['$event'])
	async likeTweet(event: any) {
		const tweetId = event.detail as string;
		await this.twitterAPI.like(tweetId);
		await this.getTweets();
	}

	clearForm() {
		this.message = '';
	}

	async logout() {
		await this.accountAPI.logout();
		this.router.navigate(['signin']);
	}
}

<honk-layout>
	<div header>
		<ul>
			<li>{{ username }}</li>
			<li>
				<button (click)="logout()" class="outline">Logout</button>
			</li>
		</ul>
	</div>

	<article main>
		<header>
			<tweet-create></tweet-create>
		</header>
		<tweet-card
			*ngFor="let tweet of tweets; let i = index"
			[key]="tweet.id"
			id="`tweet-card-{{tweet.id}}`"
			[tweetId]="tweet.id"
			[author]="tweet.author"
			[message]="tweet.message"
			[createdAt]="tweet.createdAt"
			[likes]="tweet.likes"
		></tweet-card>
	</article>
</honk-layout>

// apps/react-app/src/views/Home.tsx
import { IAccountAPI, ITwitterAPI, Tweet } from "@hexademo/domain";
import { useEffect, useState } from "react";
import "@hexademo/web-components/dist/components/tweet-card";
import { useNavigate } from "react-router-dom";
import CreateTweetComponent from "../components/CreateTweet";
import HonkLayout from "../components/HonkLayout";

type HomeViewProps = {
  twitterAPI: ITwitterAPI;
  accountAPI: IAccountAPI;
};

/**
 *
 * @param props
 */
function HomeView(props: HomeViewProps) {
  const navigate = useNavigate();
  const [username, setUsername] = useState("");
  const [tweets, setTweets] = useState([] as Array<Tweet>);

  /**
   * Get tweets
   *
   * @returns {Promise<void>}
   */
  async function listTweets() {
    const resp = await props.twitterAPI.listTweets();
    await setTweets(resp);
  }

  /**
   * Logout user
   *
   * @param e
   * @param event
   * @returns {Promise<void>}
   */
  function logout(event: Event) {
    event.preventDefault();
    return props.accountAPI.logout().then(() => {
      navigate("/");
    });
  }

  /**
   * Refresh tweet list
   *
   * @returns {void}
   */
  function refresh() {
    listTweets();
  }

  /**
   * Handle like event
   *
   * @param event
   * @returns {Promise<void>}
   */
  async function handleTweetLikedEvent(event: Event) {
    const customEvent = event as CustomEvent;
    const items = [...tweets];
    const tweetId = customEvent.detail;
    const index = items.findIndex((tweet) => tweet.id === tweetId);
    if (index === -1) return;

    const tweet = await props.twitterAPI.like(tweetId);
    items[index].likes = tweet.likes;
    setTweets(items);
  }

  useEffect(() => {
    try {
      setUsername(props.accountAPI.getUsername());
      listTweets();
    } catch (error) {
      navigate("/");
    }
  }, []);

  useEffect(() => {
    document.addEventListener("tweetLiked", handleTweetLikedEvent);
    document.addEventListener("tweetCreated", refresh);
    return () => {
      document.removeEventListener("tweetLiked", handleTweetLikedEvent);
      document.removeEventListener("tweetCreated", refresh);
    };
  }, [tweets]);

  // const tweets = await props.tweetService.listTweets();
  return (
    <HonkLayout
      header={
        <div>
          <ul>
            <li>{username}</li>
            <li>
              <button className="outline" onClick={logout}>
                Logout
              </button>
            </li>
          </ul>
        </div>
      }
      main={
        <article>
          <header>
            <CreateTweetComponent
              twitterAPI={props.twitterAPI}
              handleCreated={refresh}
            ></CreateTweetComponent>
          </header>
          {tweets.map((tweet) => (
            <tweet-card
              key={tweet.id}
              tweet-id={tweet.id}
              author={tweet.author}
              message={tweet.message}
              created-at={tweet.createdAt}
              likes={tweet.likes}
            ></tweet-card>
          ))}
        </article>
      }
    />
  );
}

export default HomeView;
