// apps/react-app/src/main.tsx
import React from "react";
import ReactDOM from "react-dom/client";
import "@picocss/pico/css/pico.css";
import "@hexademo/style";
import {
  applyPolyfills,
  defineCustomElements,
} from "@hexademo/web-components/loader";
import App from "./App";

ReactDOM.createRoot(document.getElementById("root") as HTMLElement).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>
);

applyPolyfills().then(() => {
  defineCustomElements(window);
});

// apps/angular-app/src/main.ts
import { enableProdMode } from '@angular/core';
import { platformBrowserDynamic } from '@angular/platform-browser-dynamic';
import { defineCustomElements } from '@hexademo/web-components/loader';
import '@picocss/pico/css/pico.css';
import '@hexademo/style';

import { AppModule } from './app/app.module';
import { environment } from './environments/environment';

if (environment.production) {
	enableProdMode();
}

platformBrowserDynamic()
	.bootstrapModule(AppModule)
	.catch((err) => console.error(err));

defineCustomElements(window);
