// apps/react-app/src/views/SignUp.tsx
import { IAccountAPI } from "@hexademo/domain";
import { useEffect, useState } from "react";
import { Link, useNavigate } from "react-router-dom";
import HonkLayout from "../components/HonkLayout";

type SignUpViewProps = {
  accountAPI: IAccountAPI;
};

/**
 *
 * @param props
 */
function SignUpView(props: SignUpViewProps) {
  const navigate = useNavigate();

  const [username, setUsername] = useState();
  const [password, setPassword] = useState();

  /**
   *
   * @param event
   */
  function handleSignEvent(event: Event) {
    const customEvent = event as CustomEvent;
    setUsername(customEvent.detail.username);
    setPassword(customEvent.detail.password);
    return props.accountAPI
      .register(customEvent.detail.username, customEvent.detail.password)
      .then(() => {
        navigate("/");
      });
  }

  useEffect(() => {
    window.addEventListener("signSubmited", handleSignEvent);
    return () => {
      window.removeEventListener("signSubmited", handleSignEvent);
    };
  });

  return (
    <HonkLayout
      main={
        <tweet-sign
          form-title="Register"
          btn-label="Register"
          img="https://source.unsplash.com/uymG7UVPXpI/1000x1200"
          username={username}
          password={password}
        >
          <p className="sign-option">
            Already have login and password?
            <Link to="/">Sign in</Link>
          </p>
        </tweet-sign>
      }
    />
  );
}

export default SignUpView;

// apps/angular-app/src/app/sign-up/sign-up.component.ts
import { Component, HostListener, Inject, OnInit } from '@angular/core';
import { Router } from '@angular/router';
import { IAccountAPI } from '@hexademo/domain';
import { AccountAPI } from '../injections';

@Component({
	selector: 'app-sign-up',
	templateUrl: './sign-up.component.html',
	styleUrls: ['./sign-up.component.scss'],
})
export class SignUpComponent implements OnInit {
	username = '';

	password = '';

	constructor(
		private router: Router,
		@Inject(AccountAPI) private accountAPI: IAccountAPI
	) {}

	ngOnInit(): void {}

	clearForm() {
		this.username = '';
		this.password = '';
	}

	@HostListener('signSubmited', ['$event'])
	async onSubmit(event: any) {
		this.username = event.detail.username;
		this.password = event.detail.password;
		await this.accountAPI.register(this.username, this.password);
		this.clearForm();
		this.redirect();
	}

	redirect() {
		this.router.navigate(['home']);
	}
}

<honk-layout>
		<tweet-sign main
			form-title="Register"
			btn-label="Register"
			img="https://source.unsplash.com/r6WPOp_q_xM/800x1000"
			[username]="username"
			[password]="password"
		>
			<p class="sign-option">
				Already have login and password?
				<a routerLink="/signin">Sign in</a>
			</p>
		</tweet-sign>
</honk-layout>
