// apps/react-app/src/components/CreateTweet.tsx
import { ITwitterAPI } from "@hexademo/domain";
import "@hexademo/web-components/dist/components/tweet-create";
import { useEffect, useState } from "react";

type CreateTweetProps = {
  twitterAPI: ITwitterAPI;
};

/**
 *
 * @param props
 */
function CreateTweetComponent(props: CreateTweetProps) {
  const [message, setMessage] = useState("");
  /**
   *
   * @param event
   */
  async function handleSubmitEvent(event: Event) {
    const customEvent = event as CustomEvent;
    await props.twitterAPI.tweet(customEvent.detail);
    setMessage("");
  }

  useEffect(() => {
    window.addEventListener("tweetSubmited", handleSubmitEvent);
    return () => {
      window.removeEventListener("tweetSubmited", handleSubmitEvent);
    };
  }, [message]);

  return (
    <div>
      <tweet-create message={message}></tweet-create>
    </div>
  );
}

export default CreateTweetComponent;

// apps/vue-app/src/components/CreateTweet.vue
<template>
	<tweet-create
		:message="data.message"
		@tweetsubmited="methods.onSubmit"
	></tweet-create>
</template>

<script lang="ts">
import { reactive, defineComponent } from "vue";
import "@hexademo/web-components/dist/components/tweet-create";
import { TWITTER_API } from "@/injections";
import { injectStrict } from "@/utils";

type CreateTweetData = {
	message: string;
};

export default defineComponent({
	name: "CreateTweet",
	setup() {
		const twitterAPI = injectStrict(TWITTER_API);
		const data = reactive<CreateTweetData>({ message: "" });

		function clearForm() {
			data.message = "";
		}

		async function onSubmit(event: CustomEvent) {
			data.message = event.detail;
			await twitterAPI.tweet(data.message);
			clearForm();
		}

		return {
			methods: { onSubmit },
			data,
		};
	},
});
</script>
