// apps/vue-app/src/components/HonkLayout.vue
<template>
	<div class="container">
		<header>
			<nav>
				<ul>
					<li>
						<h1>
							<RouterLink to="/">
								<img src="@/assets/new-logo.svg" alt="" /> Honk
							</RouterLink>
						</h1>
					</li>
				</ul>
				<slot name="nav"></slot>
			</nav>
		</header>
		<main>
			<slot></slot>
		</main>
	</div>
</template>

// apps/angular-app/src/app/honk-layout/honk-layout.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
	selector: 'honk-layout',
	templateUrl: './honk-layout.component.html',
	styleUrls: ['./honk-layout.component.scss'],
})
export class HonkLayoutComponent implements OnInit {
	ngOnInit(): void {}
}

	<div class="container">
		<header>
			<nav>
				<ul>
					<li>
						<h1>
							<a routerLink="/">
								<img src="../../assets/new-logo.svg" alt="" /> Honk
							</a>
						</h1>
					</li>
				</ul>
        <ng-content select="[header]"></ng-content>
			</nav>
		</header>
		<main>
			  <ng-content select="[main]"></ng-content>
		</main>
	</div>
